# Generated by Django 4.2.2 on 2023-07-03 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_price'),
        ('user', '0005_alter_cart_total_price_alter_myuser_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='CartProducts',
        ),
        migrations.AddField(
            model_name='cart',
            name='CartProducts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Products.products'),
        ),
    ]
