# Generated by Django 4.2.2 on 2023-07-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_price'),
        ('user', '0006_remove_cart_cartproducts_cart_cartproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='CartProducts',
        ),
        migrations.AddField(
            model_name='cart',
            name='CartProducts',
            field=models.ManyToManyField(blank=True, to='Products.products'),
        ),
    ]
