# Generated by Django 4.2.2 on 2023-07-03 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_price'),
        ('user', '0008_remove_cart_cartproducts_cart_cartproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='CartProducts',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Products.products')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='CartProducts',
            field=models.ManyToManyField(blank=True, to='user.cartitem'),
        ),
    ]
