# Generated by Django 4.2.2 on 2023-07-03 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_cart_cartproducts_cartitem_cart_cartproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='CartProducts',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='user.cart'),
            preserve_default=False,
        ),
    ]
