# Generated by Django 4.2.3 on 2024-01-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_orderitem_item_delete_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
