# Generated by Django 4.2.3 on 2024-01-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_price'),
        ('user', '0016_remove_cart_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartproduct',
            field=models.ManyToManyField(blank=True, null=True, related_name='cartss', to='Products.products'),
        ),
    ]
