# Generated by Django 4.2.3 on 2024-01-18 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_cart_cartproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='cart',
            new_name='user_cart',
        ),
    ]
