# Generated by Django 4.2.3 on 2024-01-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_price'),
        ('user', '0018_rename_cart_myuser_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartproduct',
            field=models.ManyToManyField(null=True, related_name='cartss', to='Products.products'),
        ),
    ]
