# Generated by Django 4.2.3 on 2024-01-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_price'),
        ('user', '0019_alter_cart_cartproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cartproduct',
            field=models.ManyToManyField(blank=True, null=True, related_name='cartss', to='Products.products'),
        ),
    ]
