/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shoe.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/shoe.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Nike_Air_Max_-_Fixed'].geometry} material={materials['default']} rotation={[-3.062, 0.011, 0.135]} />
    </group>
  )
}

useGLTF.preload('/shoe.glb')
